---
collections:
  - name: community.general
    version: "<5.0.0"
    # version to install on the pi must be lower than 5.0.0 as version 5.0.0 and higher require python 3.8+
roles:
  - name: mdsketch.teleport
